countries_info = {
    "Afghanistan": {"iso_code": "AF", "currency_name": "Afghan Afghani", "currency_code": "AFN"},
    "Albania": {"iso_code": "AL", "currency_name": "Albanian Lek", "currency_code": "ALL"},
    "Algeria": {"iso_code": "DZ", "currency_name": "Algerian Dinar", "currency_code": "DZD"},
    "Andorra": {"iso_code": "AD", "currency_name": "Euro", "currency_code": "EUR"},
    "Angola": {"iso_code": "AO", "currency_name": "Angolan Kwanza", "currency_code": "AOA"},
    "Antigua and Barbuda": {"iso_code": "AG", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    "Argentina": {"iso_code": "AR", "currency_name": "Argentine Peso", "currency_code": "ARS"},
    "Armenia": {"iso_code": "AM", "currency_name": "Armenian Dram", "currency_code": "AMD"},
    "Australia": {"iso_code": "AU", "currency_name": "Australian Dollar", "currency_code": "AUD"},
    "Austria": {"iso_code": "AT", "currency_name": "Euro", "currency_code": "EUR"},
    "Azerbaijan": {"iso_code": "AZ", "currency_name": "Azerbaijani Manat", "currency_code": "AZN"},
    "Bahamas": {"iso_code": "BS", "currency_name": "Bahamian Dollar", "currency_code": "BSD"},
    "Bahrain": {"iso_code": "BH", "currency_name": "Bahraini Dinar", "currency_code": "BHD"},
    "Bangladesh": {"iso_code": "BD", "currency_name": "Bangladeshi Taka", "currency_code": "BDT"},
    "Barbados": {"iso_code": "BB", "currency_name": "Barbadian Dollar", "currency_code": "BBD"},
    "Belarus": {"iso_code": "BY", "currency_name": "Belarusian Ruble", "currency_code": "BYN"},
    "Belgium": {"iso_code": "BE", "currency_name": "Euro", "currency_code": "EUR"},
    "Belize": {"iso_code": "BZ", "currency_name": "Belize Dollar", "currency_code": "BZD"},
    "Benin": {"iso_code": "BJ", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    "Bhutan": {"iso_code": "BT", "currency_name": "Bhutanese Ngultrum", "currency_code": "BTN"},
    "Bolivia": {"iso_code": "BO", "currency_name": "Bolivian Boliviano", "currency_code": "BOB"},
    "Bosnia and Herzegovina": {"iso_code": "BA", "currency_name": "Bosnia and Herzegovina Convertible Mark", "currency_code": "BAM"},
    "Botswana": {"iso_code": "BW", "currency_name": "Botswana Pula", "currency_code": "BWP"},
    "Brazil": {"iso_code": "BR", "currency_name": "Brazilian Real", "currency_code": "BRL"},
    "Brunei": {"iso_code": "BN", "currency_name": "Brunei Dollar", "currency_code": "BND"},
    "Bulgaria": {"iso_code": "BG", "currency_name": "Bulgarian Lev", "currency_code": "BGN"},
    "Burkina Faso": {"iso_code": "BF", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    "Burundi": {"iso_code": "BI", "currency_name": "Burundian Franc", "currency_code": "BIF"},
    "Cabo Verde": {"iso_code": "CV", "currency_name": "Cape Verdean Escudo", "currency_code": "CVE"},
    "Cambodia": {"iso_code": "KH", "currency_name": "Cambodian Riel", "currency_code": "KHR"},
    "Cameroon": {"iso_code": "CM", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    "Canada": {"iso_code": "CA", "currency_name": "Canadian Dollar", "currency_code": "CAD"},
    "Central African Republic": {"iso_code": "CF", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    "Chad": {"iso_code": "TD", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    "Chile": {"iso_code": "CL", "currency_name": "Chilean Peso", "currency_code": "CLP"},
    "China": {"iso_code": "CN", "currency_name": "Chinese Yuan", "currency_code": "CNY"},
    "Colombia": {"iso_code": "CO", "currency_name": "Colombian Peso", "currency_code": "COP"},
    "Comoros": {"iso_code": "KM", "currency_name": "Comorian Franc", "currency_code": "KMF"},
    "Congo, Democratic Republic of the Congo": {"iso_code": "CD", "currency_name": "Congolese Franc", "currency_code": "CDF"},
    "Congo, Republic of the Congo": {"iso_code": "CG", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    "Costa Rica": {"iso_code": "CR", "currency_name": "Costa Rican Colón", "currency_code": "CRC"},
    "Croatia": {"iso_code": "HR", "currency_name": "Euro", "currency_code": "EUR"},
    "Cuba": {"iso_code": "CU", "currency_name": "Cuban Peso", "currency_code": "CUP"},
    "Cyprus": {"iso_code": "CY", "currency_name": "Euro", "currency_code": "EUR"},
    "Czechia": {"iso_code": "CZ", "currency_name": "Czech Koruna", "currency_code": "CZK"},
    "Denmark": {"iso_code": "DK", "currency_name": "Danish Krone", "currency_code": "DKK"},
    "Djibouti": {"iso_code": "DJ", "currency_name": "Djiboutian Franc", "currency_code": "DJF"},
    "Dominica": {"iso_code": "DM", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    "Dominican Republic": {"iso_code": "DO", "currency_name": "Dominican Peso", "currency_code": "DOP"},
    "Ecuador": {"iso_code": "EC", "currency_name": "US Dollar", "currency_code": "USD"},
    "Egypt": {"iso_code": "EG", "currency_name": "Egyptian Pound", "currency_code": "EGP"},
    "El Salvador": {"iso_code": "SV", "currency_name": "US Dollar", "currency_code": "USD"},
    "Equatorial Guinea": {"iso_code": "GQ", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    "Eritrea": {"iso_code": "ER", "currency_name": "Eritrean Nakfa", "currency_code": "ERN"},
    "Estonia": {"iso_code": "EE", "currency_name": "Euro", "currency_code": "EUR"},
    "Eswatini": {"iso_code": "SZ", "currency_name": "Swazi Lilangeni", "currency_code": "SZL"},
    "Ethiopia": {"iso_code": "ET", "currency_name": "Ethiopian Birr", "currency_code": "ETB"},
    "Fiji": {"iso_code": "FJ", "currency_name": "Fijian Dollar", "currency_code": "FJD"},
    "Finland": {"iso_code": "FI", "currency_name": "Euro", "currency_code": "EUR"},
    "France": {"iso_code": "FR", "currency_name": "Euro", "currency_code": "EUR"},
    "Gabon": {"iso_code": "GA", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    "Gambia": {"iso_code": "GM", "currency_name": "Gambian Dalasi", "currency_code": "GMD"},
    "Georgia": {"iso_code": "GE", "currency_name": "Georgian Lari", "currency_code": "GEL"},
    "Germany": {"iso_code": "DE", "currency_name": "Euro", "currency_code": "EUR"},
    "Ghana": {"iso_code": "GH", "currency_name": "Ghanaian Cedi", "currency_code": "GHS"},
    "Greece": {"iso_code": "GR", "currency_name": "Euro", "currency_code": "EUR"},
    "Grenada": {"iso_code": "GD", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    "Guatemala": {"iso_code": "GT", "currency_name": "Guatemalan Quetzal", "currency_code": "GTQ"},
    "Guinea": {"iso_code": "GN", "currency_name": "Guinean Franc", "currency_code": "GNF"},
    "Guinea-Bissau": {"iso_code": "GW", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    "Guyana": {"iso_code": "GY", "currency_name": "Guyanese Dollar", "currency_code": "GYD"},
    "Haiti": {"iso_code": "HT", "currency_name": "Haitian Gourde", "currency_code": "HTG"},
    "Honduras": {"iso_code": "HN", "currency_name": "Honduran Lempira", "currency_code": "HNL"},
    "Hungary": {"iso_code": "HU", "currency_name": "Hungarian Forint", "currency_code": "HUF"},
    "Iceland": {"iso_code": "IS", "currency_name": "Icelandic Króna", "currency_code": "ISK"},
    "India": {"iso_code": "IN", "currency_name": "Indian Rupee", "currency_code": "INR"},
    "Indonesia": {"iso_code": "ID", "currency_name": "Indonesian Rupiah", "currency_code": "IDR"},
    "Iran": {"iso_code": "IR", "currency_name": "Iranian Rial", "currency_code": "IRR"},
    "Iraq": {"iso_code": "IQ", "currency_name": "Iraqi Dinar", "currency_code": "IQD"},
    "Ireland": {"iso_code": "IE", "currency_name": "Euro", "currency_code": "EUR"},
    "Israel": {"iso_code": "IL", "currency_name": "Israeli New Shekel", "currency_code": "ILS"},
    "Italy": {"iso_code": "IT", "currency_name": "Euro", "currency_code": "EUR"},
    "Jamaica": {"iso_code": "JM", "currency_name": "Jamaican Dollar", "currency_code": "JMD"},
    "Japan": {"iso_code": "JP", "currency_name": "Japanese Yen", "currency_code": "JPY"},
    "Jordan": {"iso_code": "JO", "currency_name": "Jordanian Dinar", "currency_code": "JOD"},
    "Kazakhstan": {"iso_code": "KZ", "currency_name": "Kazakhstani Tenge", "currency_code": "KZT"},
    "Kenya": {"iso_code": "KE", "currency_name": "Kenyan Shilling", "currency_code": "KES"},
    "Kiribati": {"iso_code": "KI", "currency_name": "Australian Dollar", "currency_code": "AUD"},
    "Korea, North": {"iso_code": "KP", "currency_name": "North Korean Won", "currency_code": "KPW"},
    "Korea, South": {"iso_code": "KR", "currency_name": "South Korean Won", "currency_code": "KRW"},
    "Kuwait": {"iso_code": "KW", "currency_name": "Kuwaiti Dinar", "currency_code": "KWD"},
    "Kyrgyzstan": {"iso_code": "KG", "currency_name": "Kyrgyzstani Som", "currency_code": "KGS"},
    "Laos": {"iso_code": "LA", "currency_name": "Lao Kip", "currency_code": "LAK"},
    "Latvia": {"iso_code": "LV", "currency_name": "Euro", "currency_code": "EUR"},
    "Lebanon": {"iso_code": "LB", "currency_name": "Lebanese Pound", "currency_code": "LBP"},
    "Lesotho": {"iso_code": "LS", "currency_name": "Lesotho Loti", "currency_code": "LSL"},
    "Liberia": {"iso_code": "LR", "currency_name": "Liberian Dollar", "currency_code": "LRD"},
    "Libya": {"iso_code": "LY", "currency_name": "Libyan Dinar", "currency_code": "LYD"},
    "Liechtenstein": {"iso_code": "LI", "currency_name": "Swiss Franc", "currency_code": "CHF"},
    "Lithuania": {"iso_code": "LT", "currency_name": "Euro", "currency_code": "EUR"},
    "Luxembourg": {"iso_code": "LU", "currency_name": "Euro", "currency_code": "EUR"},
    "Madagascar": {"iso_code": "MG", "currency_name": "Malagasy Ariary", "currency_code": "MGA"},
    "Malawi": {"iso_code": "MW", "currency_name": "Malawian Kwacha", "currency_code": "MWK"},
    "Malaysia": {"iso_code": "MY", "currency_name": "Malaysian Ringgit", "currency_code": "MYR"},
    "Maldives": {"iso_code": "MV", "currency_name": "Maldivian Rufiyaa", "currency_code": "MVR"},
    "Mali": {"iso_code": "ML", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    "Malta": {"iso_code": "MT", "currency_name": "Euro", "currency_code": "EUR"},
    "Marshall Islands": {"iso_code": "MH", "currency_name": "US Dollar", "currency_code": "USD"},
    "Mauritania": {"iso_code": "MR", "currency_name": "Mauritanian Ouguiya", "currency_code": "MRU"},
    "Mauritius": {"iso_code": "MU", "currency_name": "Mauritian Rupee", "currency_code": "MUR"},
    "Mexico": {"iso_code": "MX", "currency_name": "Mexican Peso", "currency_code": "MXN"},
    "Micronesia": {"iso_code": "FM", "currency_name": "US Dollar", "currency_code": "USD"},
    "Moldova": {"iso_code": "MD", "currency_name": "Moldovan Leu", "currency_code": "MDL"},
    "Monaco": {"iso_code": "MC", "currency_name": "Euro", "currency_code": "EUR"},
    "Mongolia": {"iso_code": "MN", "currency_name": "Mongolian Tögrög", "currency_code": "MNT"},
    "Montenegro": {"iso_code": "ME", "currency_name": "Euro", "currency_code": "EUR"},
    "Morocco": {"iso_code": "MA", "currency_name": "Moroccan Dirham", "currency_code": "MAD"},
    "Mozambique": {"iso_code": "MZ", "currency_name": "Mozambican Metical", "currency_code": "MZN"},
    "Myanmar": {"iso_code": "MM", "currency_name": "Myanmar Kyat", "currency_code": "MMK"},
    "Namibia": {"iso_code": "NA", "currency_name": "Namibian Dollar", "currency_code": "NAD"},
    "Nauru": {"iso_code": "NR", "currency_name": "Australian Dollar", "currency_code": "AUD"},
    "Nepal": {"iso_code": "NP", "currency_name": "Nepalese Rupee", "currency_code": "NPR"},
    "Netherlands": {"iso_code": "NL", "currency_name": "Euro", "currency_code": "EUR"},
    "New Zealand": {"iso_code": "NZ", "currency_name": "New Zealand Dollar", "currency_code": "NZD"},
    "Nicaragua": {"iso_code": "NI", "currency_name": "Nicaraguan Córdoba", "currency_code": "NIO"},
    "Niger": {"iso_code": "NE", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    "Nigeria": {"iso_code": "NG", "currency_name": "Nigerian Naira", "currency_code": "NGN"},
    "North Macedonia": {"iso_code": "MK", "currency_name": "Macedonian Denar", "currency_code": "MKD"},
    "Norway": {"iso_code": "NO", "currency_name": "Norwegian Krone", "currency_code": "NOK"},
    "Oman": {"iso_code": "OM", "currency_name": "Omani Rial", "currency_code": "OMR"},
    "Pakistan": {"iso_code": "PK", "currency_name": "Pakistani Rupee", "currency_code": "PKR"},
    "Palau": {"iso_code": "PW", "currency_name": "US Dollar", "currency_code": "USD"},
    "Panama": {"iso_code": "PA", "currency_name": "Panamanian Balboa", "currency_code": "PAB"},
    "Papua New Guinea": {"iso_code": "PG", "currency_name": "Papua New Guinean Kina", "currency_code": "PGK"},
    "Paraguay": {"iso_code": "PY", "currency_name": "Paraguayan Guaraní", "currency_code": "PYG"},
    "Peru": {"iso_code": "PE", "currency_name": "Peruvian Sol", "currency_code": "PEN"},
    "Philippines": {"iso_code": "PH", "currency_name": "Philippine Peso", "currency_code": "PHP"},
    "Poland": {"iso_code": "PL", "currency_name": "Polish Złoty", "currency_code": "PLN"},
    "Portugal": {"iso_code": "PT", "currency_name": "Euro", "currency_code": "EUR"},
    "Qatar": {"iso_code": "QA", "currency_name": "Qatari Riyal", "currency_code": "QAR"},
    "Romania": {"iso_code": "RO", "currency_name": "Romanian Leu", "currency_code": "RON"},
    "Russia": {"iso_code": "RU", "currency_name": "Russian Ruble", "currency_code": "RUB"},
    "Rwanda": {"iso_code": "RW", "currency_name": "Rwandan Franc", "currency_code": "RWF"},
    "Saint Kitts and Nevis": {"iso_code": "KN", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    "Saint Lucia": {"iso_code": "LC", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    "Saint Vincent and the Grenadines": {"iso_code": "VC", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    "Samoa": {"iso_code": "WS", "currency_name": "Samoan Tālā", "currency_code": "WST"},
    "San Marino": {"iso_code": "SM", "currency_name": "Euro", "currency_code": "EUR"},
    "Sao Tome and Principe": {"iso_code": "ST", "currency_name": "São Tomé and Príncipe Dobra", "currency_code": "STN"},
    "Saudi Arabia": {"iso_code": "SA", "currency_name": "Saudi Riyal", "currency_code": "SAR"},
    "Senegal": {"iso_code": "SN", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    "Serbia": {"iso_code": "RS", "currency_name": "Serbian Dinar", "currency_code": "RSD"},
    "Seychelles": {"iso_code": "SC", "currency_name": "Seychellois Rupee", "currency_code": "SCR"},
    "Sierra Leone": {"iso_code": "SL", "currency_name": "Sierra Leonean Leone", "currency_code": "SLL"},
    "Singapore": {"iso_code": "SG", "currency_name": "Singapore Dollar", "currency_code": "SGD"},
    "Slovakia": {"iso_code": "SK", "currency_name": "Euro", "currency_code": "EUR"},
    "Slovenia": {"iso_code": "SI", "currency_name": "Euro", "currency_code": "EUR"},
    "Solomon Islands": {"iso_code": "SB", "currency_name": "Solomon Islands Dollar", "currency_code": "SBD"},
    "Somalia": {"iso_code": "SO", "currency_name": "Somali Shilling", "currency_code": "SOS"},
    "South Africa": {"iso_code": "ZA", "currency_name": "South African Rand", "currency_code": "ZAR"},
    "South Sudan": {"iso_code": "SS", "currency_name": "South Sudanese Pound", "currency_code": "SSP"},
    "Spain": {"iso_code": "ES", "currency_name": "Euro", "currency_code": "EUR"},
    "Sri Lanka": {"iso_code": "LK", "currency_name": "Sri Lankan Rupee", "currency_code": "LKR"},
    "Sudan": {"iso_code": "SD", "currency_name": "Sudanese Pound", "currency_code": "SDG"},
    "Suriname": {"iso_code": "SR", "currency_name": "Surinamese Dollar", "currency_code": "SRD"},
    "Sweden": {"iso_code": "SE", "currency_name": "Swedish Krona", "currency_code": "SEK"},
    "Switzerland": {"iso_code": "CH", "currency_name": "Swiss Franc", "currency_code": "CHF"},
    "Syria": {"iso_code": "SY", "currency_name": "Syrian Pound", "currency_code": "SYP"},
    "Tajikistan": {"iso_code": "TJ", "currency_name": "Tajikistani Somoni", "currency_code": "TJS"},
    "Tanzania": {"iso_code": "TZ", "currency_name": "Tanzanian Shilling", "currency_code": "TZS"},
    "Thailand": {"iso_code": "TH", "currency_name": "Thai Baht", "currency_code": "THB"},
    "Timor-Leste": {"iso_code": "TL", "currency_name": "US Dollar", "currency_code": "USD"},
    "Togo": {"iso_code": "TG", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    "Tonga": {"iso_code": "TO", "currency_name": "Tongan Paʻanga", "currency_code": "TOP"},
    "Trinidad and Tobago": {"iso_code": "TT", "currency_name": "Trinidad and Tobago Dollar", "currency_code": "TTD"},
    "Tunisia": {"iso_code": "TN", "currency_name": "Tunisian Dinar", "currency_code": "TND"},
    "Turkey": {"iso_code": "TR", "currency_name": "Turkish Lira", "currency_code": "TRY"},
    "Turkmenistan": {"iso_code": "TM", "currency_name": "Turkmenistan Manat", "currency_code": "TMT"},
    "Tuvalu": {"iso_code": "TV", "currency_name": "Australian Dollar", "currency_code": "AUD"},
    "Uganda": {"iso_code": "UG", "currency_name": "Ugandan Shilling", "currency_code": "UGX"},
    "Ukraine": {"iso_code": "UA", "currency_name": "Ukrainian Hryvnia", "currency_code": "UAH"},
    "United Arab Emirates": {"iso_code": "AE", "currency_name": "UAE Dirham", "currency_code": "AED"},
    "United Kingdom": {"iso_code": "GB", "currency_name": "Pound Sterling", "currency_code": "GBP"},
    "United States": {"iso_code": "US", "currency_name": "US Dollar", "currency_code": "USD"},
    "Uruguay": {"iso_code": "UY", "currency_name": "Uruguayan Peso", "currency_code": "UYU"},
    "Uzbekistan": {"iso_code": "UZ", "currency_name": "Uzbekistani So'm", "currency_code": "UZS"},
    "Vanuatu": {"iso_code": "VU", "currency_name": "Vanuatu Vatu", "currency_code": "VUV"},
    "Vatican City": {"iso_code": "VA", "currency_name": "Euro", "currency_code": "EUR"},
    "Venezuela": {"iso_code": "VE", "currency_name": "Venezuelan Bolívar", "currency_code": "VES"},
    "Vietnam": {"iso_code": "VN", "currency_name": "Vietnamese Đồng", "currency_code": "VND"},
    "Yemen": {"iso_code": "YE", "currency_name": "Yemeni Rial", "currency_code": "YER"},
    "Zambia": {"iso_code": "ZM", "currency_name": "Zambian Kwacha", "currency_code": "ZMW"},
    "Zimbabwe": {"iso_code": "ZW", "currency_name": "Zimbabwean Dollar", "currency_code": "ZWL"}
}